- name: variables from play
  hosts: web
  vars_files: 
  - variables.yaml
  tasks:
  - name: Check variables
    ansible.builtin.debug:
     msg: "I am Learning {{course}}, I am taking training from {{Trainer}}, Duration is {{Duration}}"
