- name: variable from play level
  hosts: web
  tasks:
  - name: check variable
    ansible.builtin.debug:
     msg: "Hi, Iam taking {{Course}} trainig, My Trainer is {{Trainer}}, Duration is {{Duration}}"
