- name: vars from play
  hosts: web
  vars_files:
   - variables.yaml
  #vars_prompt:
  #- name: person
   # prompt: please enter your name
   # private: false
  #- name: WISHES
    #prompt: please enter wishes
    #private: false
  #vars:
   #person: "Sravani from PLAY"
   #WISHES: "Morning From PlAY"
  tasks:
  - name: check files
    #vars:
     #person: "Sravani from TASK"
     #WISHES: "Morning From TASK"
    ansible.builtin.debug:
     msg: "Hello {{person}}, Good {{WISHES}}"

#args(command line)
#tasks
#prompt
#PLAY