- name: datatypes
  hosts: web
  vars:
   NAME: sivakumar #key value
   SKILLS: #list types
   - DevOps
   - shell
   - ansible
   - linux
   EXPERIENCE: #map
     DevOps: 7
     AWS: 6
     Docker: 3
   Trainer: true #boolena
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
     msg: "name: {{NAME}}"
  - name: print list type
    ansible.builtin.debug:
     msg: "skills are {{SKILLS}}"
  - name: map
    ansible.builtin.debug:
     msg: "experience is {{EXPERIENCE}}"
  - name: check boolean
    ansible.builtin.debug:
     msg: "is he trainer: {{TRAINER}}"

    
