- name: conditions
  hosts: web
  tasks:
  - name: check roboshop user
    ansible.builtin.command: id roboshop
    register: user #user is bariable name
    ignore_errors: true

  - name: print variable value
    ansible.builtin.debug:
     msg: "user output is: {{user}}"

  - name: print exit status
    ansible.builtin.debug
     msg: "status is: {{user.rc}}""
    